PROGRAM MEDIA_HORARIA


!---------------------------------------------------------------------------------------------------
!UNIVERSIDADE FEDERAL DE ALAGOAS - UFAL
!CAMPUS DE ENGENHARIA E CIENCIAS AGRARIAS - CECA
!LABORATORIO DE IRRIGAÇÃO E AGROMETEOROLOGIA - LIA
!PROGRAMA PARA CALCULAR A MÉDIA DA TEMPERATURA E UMIDADE DIÁRIA
!DADOS FORNECIDOS PELA ESTAÇÃO AGROMETEOROLOGICA - CECA\UFAL
!---------------------------------------------------------------------------------------------------

IMPLICIT NONE
 
REAL,DIMENSION(:),ALLOCATABLE::CHUVA, CHUVADV, U2, U2MED, TMIN,TMED, TMAX, TMAXDV,TMEDDV, TMINDV, U2MEDDV, UR, URMAX, URMED, URMIN, URMAXDV,URMEDDV, URMINDV
INTEGER,DIMENSION(:),ALLOCATABLE:: MESV,DIAV,ANO, DIA, MES, HORA, MINUT
INTEGER:: NUM_DIA ! NUM DE DIAS DO ARQUIVO, CALCULADO PELA FUNCAO NDIA

REAL :: NUM_HORA !NÚMERO DE HORAS DO ARQUIVO, CALCULADO PELA FUNÇÃO NHORA
REAL :: Lixo	
	
	
CALL READ_FILEA("dados.txt")

CONTAINS

FUNCTION NDIA(VEC)
INTEGER,DIMENSION(:),INTENT(IN):: VEC
INTEGER NDIA
INTEGER I, NDATA

 NDATA = SIZE(VEC)
 I = 1
 NDIA = 1

DO WHILE(I < NDATA)
	DO WHILE(VEC(I+1) == VEC(I) .AND. I< NDATA)
 	I = I +1  
 	ENDDO
	 I = I + 1
 	NDIA = NDIA + 1
ENDDO
 	IF (VEC(NDATA) == VEC(NDATA-1)) NDIA = NDIA -1  
RETURN

END FUNCTION

FUNCTION NHORA(VEC)
INTEGER,DIMENSION(:),INTENT(IN):: VEC
INTEGER NHORA
INTEGER I, J, K, INDICE 
REAL : VHORA, SOMAT, MEDIAT, SOMAH, MEDIAH, SOMAU2, MEDIAU2, DIAH, 

	
VHORA=SIZE(VEC)
I = 1
NHORA =1

DO WHILE(I < VHORA) 
K=0  
  DO WHILE(HORA (I))= HORA(I+1)
  	K=K+1
	I= I + 1
	INDICE(K) = I
	ENDDO
		K = K + 1
		I = I + 1
		INDICE(K)=I
		J = J + 1
			
		TMAXDV(J) = MAXVAL(TMAX(INDICE))
		TMINDV(J) = MAXVAL(TMIN(INDICE))
		UMAXDV(J) = MAXVAL(U2(INDICE))
		UMMINDV(J) = MAXVAL(U2(INDICE))
		DIAH(J) = DIA(I)
		HORA(J) = HORA(I)		
	END DO



END FUNCTION

SUBROUTINE READ_FILEA(FNAME)

CHARACTER(*):: FNAME
INTEGER:: N,IO,I,K,J
CHARACTER(LEN=1):: LIXO
CHARACTER(LEN=20):: DAT
REAL:: TMAXD, TMIND, SOMAT, SOMAU2

	IO=0

OPEN(1,FILE=FNAME,STATUS="OLD")

DO I=1,4       !LOOP P/ PULAR AS PRIMEIRAS LINHAS
	READ(1,*)
ENDDO
	! CONTAR AS LINHAS DO ARQUIVO
	N=0
DO WHILE (IO == 0) 
	READ (1, *, IOSTAT = IO)LIXO
	N= N+1   !NÚMERO DE TERMOS
ENDDO
	N= N-1

CLOSE(1) ! FECHA ARQUIVO 1


!ADCIONAR ALLOCATE PARA CADA CULUNA DE VARIÁVEL. OBS: NÃO FUNCIONA COM VÍRGULA.
ALLOCATE(TMAX(N)) 
ALLOCATE(TMIN(N)) 
ALLOCATE(TMED(N))
ALLOCATE(U2(N))
ALLOCATE(CHUVA(N))
ALLOCATE(UR(N))
ALLOCATE(URMAX(N))
ALLOCATE(URMIN(N))
ALLOCATE(ANO(N))
ALLOCATE(MES(N))
ALLOCATE(DIA(N))
ALLOCATE(HORA(N))
ALLOCATE(MINUT(N))

OPEN(1,FILE=FNAME,STATUS="OLD")
OPEN(2,FILE="SAIDA.txt",STATUS="REPLACE")

DO I=1,4       !LOOP P/ PULAR AS PRIMEIRAS LINHAS
	READ(1,*)
ENDDO
	
DO I=1,N
	READ(1,*)DAT,LIXO,LIXO,TMAX(I),TMIN(I),UR(I), U2(I), GS(I), RG(I)
	READ(DAT(1:4),"(I)") ANO(I) !FOR CHARACTER CONVERTS TO INTEGER
	READ(DAT(6:7),"(I)") MES(I)
	READ(DAT(9:10),"(I)") DIA(I)
	READ(DAT(12:13),"(I)") HORA(I)
	READ(DAT(15:16),"(I)") MINUT(I)
ENDDO

CLOSE(1)


	
		
		
10 FORMAT( 'LINHA', T8, 'DIA', T12, 'MES', T20, 'CHUVA', T29, 'VVMED', T37, 'TMAX', T47, 'TMED', T57, 'TMIN', &
		& T67, 'URMAX', T77, 'URMED', T87, 'URMIN'/ 14('-'), T20, '(MM)', T29, '(M/S)', T36, '(GRAUS)', T46, '(GRAUS)', &
		& T56, '(GRAUS)', T68, '(%)', T78, '(%)', T88, '(%)'/ 91('-') / )
20 FORMAT( I3 T8, I2 T12, I2 T16, F8.2 T25, F8.2 T34,F8.2 T44,F8.2 T54, F8.2 T64, F8.2 T74, F8.2 T84, F8.2 T94 )

	WRITE(2,10)
			
DO I=1,J
		
	WRITE(2,20)I, DIAV(I), MESV(I),CHUVADV(I),U2MEDDV(I), TMAXDV(I),TMEDDV(I), TMINDV(I), URMAXDV(I),URMEDDV(I), URMINDV(I)
ENDDO
	
	
CLOSE (1)
END SUBROUTINE
END PROGRAM